version: '3.8'

services:
  db:
    image: postgres:16
    container_name: appweb.lowerappname-db
    environment:
      POSTGRES_USER: appweb.lowerappnameuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appweb.lowerappnamedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: