version: '3.8'

services:
  db:
    image: postgres:16
    container_name: somesimplify-db
    environment:
      POSTGRES_USER: somesimplifyuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: somesimplifydb
    volumes:
      - somesimplify_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  somesimplify_data: