version: '3.8'

services:
  db:
    image: postgres:16
    container_name: templateapp-db
    environment:
      POSTGRES_USER: templateappuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: templateappdb
    volumes:
      - templateapp_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  templateapp_data: